on: [push]
jobs:
  build-and-deploy:
    env:
      REGISTRY_URL: kodeyacr.azurecr.io
      NAMESPACE: kodeyaks8c74
      IMAGE_NAME: kodeyaks
      SECRET_NAME: kodeyaks

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_URL }}
        username: ${{ secrets.kodeyacr_812b2_username }} 
        password: ${{ secrets.kodeyacr_812b2_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t  $REGISTRY_URL/$IMAGE_NAME:${{ github.sha }}
        docker push $REGISTRY_URL/$IMAGE_NAME:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.kodeyAks_812b2 }} 
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE  }}
        container-registry-url: ${{ env.REGISTRY_URL }}
        container-registry-username: ${{ secrets.kodeyacr_812b2_username }}
        container-registry-password: ${{ secrets.kodeyacr_812b2_password }}
        secret-name: ${{ env.SECRET_NAME  }}
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: ${{ env.NAMESPACE  }}
        manifests: |
          .devcontainer/manifests/deployment.yml
          .devcontainer/manifests/service.yml
          
        images: |
          ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME  }}:${{ github.sha }}
        imagepullsecrets: |
          ${{ env.SECRET_NAME  }}
